name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/

  deploy:
    name: Deploy to SFTP
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist/

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy
        env:
          HOST: ${{ secrets.DEPLOY_FTP_HOST }}
          USER: ${{ secrets.DEPLOY_FTP_USERNAME }}
          PASSWORD: ${{ secrets.DEPLOY_FTP_PASSWORD }}
          PORT: ${{ secrets.DEPLOY_FTP_PORT }}
        run: |
          lftp -vv -c "
          set net:timeout 5;
          set net:max-retries 2;
          set net:reconnect-interval-base 5;
          set ssl:verify-certificate no;
          open -u $USER,$PASSWORD $HOST:$PORT;
          mirror dist / -Renv --parallel=10
          "
